[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:node_exporter]
command=/node_exporter
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true