# Generated by Django 5.0.4 on 2024-05-01 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_friendinvitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(related_name='tournaments', through='core.Participation', to=settings.AUTH_USER_MODEL),
        ),
    ]
