# Generated by Django 5.0.4 on 2024-04-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_is_draft_game_is_finished_game_roundgame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='nickname',
        ),
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
