# Generated by Django 5.0.4 on 2024-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_participation_nickname_participation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
