# Generated by Django 5.0.4 on 2024-04-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_login_otp_user_login_otp_used_user_otp_base32_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otpauth_url',
            new_name='otp_auth_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_otp',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
