# Generated by Django 5.0.4 on 2024-05-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tournament_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
