# Generated by Django 5.0.4 on 2024-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tournament_has_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentinvitation',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentinvitation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('canceled', 'Canceled'), ('finished', 'Finished')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='player1_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('playing', 'Playing')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('playing', 'Playing')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='GameInvitation',
        ),
        migrations.DeleteModel(
            name='TournamentInvitation',
        ),
    ]
