# Generated by Django 5.0.4 on 2024-04-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_otpauth_url_user_otp_auth_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
