# Generated by Django 5.0.4 on 2024-04-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='name',
        ),
    ]
