# Generated by Django 3.2.23 on 2024-02-06 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240123_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_room', models.CharField(max_length=255)),
                ('Users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
