# Generated by Django 5.0.4 on 2024-04-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tournamentinvitation_tournament_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
