# Generated by Django 3.2.24 on 2024-02-14 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gameroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='name_room',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gameroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gameroom')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.score')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
