# Generated by Django 5.0.4 on 2024-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_room_participants_delete_message_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
