# Generated by Django 5.0.4 on 2024-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/user_avatars/default_avatar.png', null=True, upload_to='user_avatars/'),
        ),
    ]
