# Generated by Django 5.0.4 on 2024-04-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatars/default-avatar.png', null=True, upload_to='user_avatars/'),
        ),
    ]
