# Generated by Django 3.2.24 on 2024-02-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240214_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='name',
            field=models.CharField(default='000000', max_length=255),
        ),
    ]
