# Generated by Django 3.2.24 on 2024-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gameroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
