# Generated by Django 3.2.24 on 2024-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240214_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='score_p1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='score',
            name='score_p2',
            field=models.IntegerField(default='0'),
        ),
    ]
