# Generated by Django 5.0.4 on 2024-04-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_game_user_remove_gameroom_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('user', 'tournament')},
        ),
    ]
