# Generated by Django 3.2.24 on 2024-02-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240214_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score_p1',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_p2',
        ),
    ]
