# Generated by Django 5.0.4 on 2024-04-18 11:45

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_friendinvitation_gameinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendinvitation',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='friendinvitation',
            name='player2',
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='user1',
            field=models.ForeignKey(default=core.models.get_system_user, on_delete=django.db.models.deletion.CASCADE, related_name='friend_invitations_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendinvitation',
            name='user2',
            field=models.ForeignKey(default=core.models.get_system_user, on_delete=django.db.models.deletion.CASCADE, related_name='friend_invitations_as_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
