# Generated by Django 5.0.4 on 2024-04-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_is_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user_avatars/default-avatar.png', upload_to='user_avatars/'),
        ),
    ]
