# Generated by Django 5.0.4 on 2024-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_tournamentinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
