# Generated by Django 5.0.4 on 2024-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_tournamentinvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
