# Generated by Django 3.2.24 on 2024-02-14 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20240214_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default='0')),
                ('has_won', models.BooleanField(default='False')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='Users',
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(default='default', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='default', max_length=25),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AddField(
            model_name='gameuser',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.game'),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='player',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(through='core.GameUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
