# Generated by Django 3.2.24 on 2024-02-14 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20240214_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
