# Generated by Django 3.2.23 on 2024-01-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
